### PR TITLE
HTTPServerRequest: initialize localAddress and remoteAddress lazily

### PR DESCRIPTION
**Pull request by pushkarnk**
In `HTTPServerRequest` private vars `localAddress` and `localAddressPort` are used only in the implementation of the `urlURL` property. However, they are always initialised in the `HTTPServerRequest` initialiser. We can move their initialisation within the `urlURL` implementation.

### CODE REVIEW

**Comment by pushkarnk** [comment]
`ChanneHandlerContext.localAddress` may be accessed only one the event loop associated with the channel handler context. This change isn't feasible. Closing.

**Comment by pushkarnk** [comment]
@nethraravindran I've pushed a commit that initialises `remoteAddress` in a lazy manner

**Comment by pushkarnk** [comment]
@nethraravindran I've pushed a few more changes. Could you please review the new patch and approve? Thanks!

**Comment by nethraravindran** [comment]
@pushkarnk I guess we can now re-use `func run(_ task: @escaping () -> Void) -> EventLoopFuture<Void>?` in `ClientRequest` as well

**Pull request merged**
